from selenium.webdriver.common.by import By

START_NOW_BUTTON = (By.CLASS_NAME, 'button_root__1hQz-.button_primary__2-Qrd')
EMAIL_INPUT_FIELD = (By.ID, 'email')
USERNAME_INPUT_FIELD = (By.ID, 'userName')
FIRST_NAME_INPUT_FIELD = (By.ID, 'firstName')
LAST_NAME_INPUT_FIELD = (By.ID, 'lastName')
MOBILE_PHONE_INPUT_FIELD = (By.ID, 'phone')
MOBILE_VALIDATION_ERROR_HINT = (By.CSS_SELECTOR, '.contact-information-form_phoneField__2iJiw small')
CANCEL_BUTTON = (By.ID, 'registration-form-cancel-button')
NEXT_BUTTON = (By.ID, 'registration-form-submit-button')
CREATE_YOUR_ACCOUNT_STEPS_HEADER = (By.CSS_SELECTOR, '[class="p-dialog-header"] [class="p-dialog-title"]')
EMAIL_ERROR_HINT = (By.CSS_SELECTOR, '[class="text-field_error__1kbJu"]')
EMAIL_IS_REQUIRED_ERROR_HINT = (By.CSS_SELECTOR, '.contact-information-form_emailField__z1-19 small')
ALREADY_REGISTERED_EMAIL_ERROR_HINT = (By.CSS_SELECTOR, '.text-field_error__1kbJu span')
USERNAME_IS_REQUIRED_ERROR_HINT = (By.CSS_SELECTOR, '.contact-information-form_userNameField__HZQhu small')
ALREADY_REGISTERED_USERNAME_ERROR_HINT = (By.XPATH, '//small[text()="This Username is already exists"]')
FIRST_NAME_IS_REQUIRED_ERROR_HINT = (By.CSS_SELECTOR, '.contact-information-form_firstNameField__2v_9f small')
LAST_NAME_IS_REQUIRED_ERROR_HINT = (By.CSS_SELECTOR, '.contact-information-form_lastNameField__bi2Ma small')
PASSWORD_INPUT_FIELD = (By.ID, 'password')
PASSWORD_VALIDATION_ERROR_HINT_UPPER_CASE = (
    By.XPATH,
    '//small[text()="Password should be contain at least 1 upper-cased letter(s)"]')
PASSWORD_VALIDATION_ERROR_HINT_NUMBER = (
    By.XPATH,
    '//small[text()="Password should be contain at least 1 number(s)"]')
PASSWORD_VALIDATION_ERROR_HINT_SYMBOL = (
    By.XPATH,
    '//small[text()="Password should be contain at least 1 symbol(s)"]')
PASSWORD_RANGE_ERROR_HINT = (By.XPATH, '//small[text()="Password range should be 14-200 characters"]')
CONFIRM_PASSWORD_VALIDATION_ERROR_HINT = (
    By.XPATH, '//div[@class="password-field_root__1Hp1g"]/small[text()="Confirm password does not match"]')
CONFIRM_PASSWORD_INPUT_FIELD = (By.ID, 'confirmPassword')
CONFIRM_PASSWORD_ERROR_HINT = (By.XPATH, '//small[text()="Confirm password does not match"]')
PREVIOUS_BUTTON = (By.ID, 'registration-form-back-button')
COMPANY_NAME_INPUT_FIELD = (By.ID, 'companyName')
COMPANY_NAME_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="Company Name is required"]')
COMPANY_WEB_SITE_URL_INPUT_FIELD = (By.ID, 'website')
COMPANY_INVALID_URL_ERROR_HINT = (By.XPATH, '//small[text()="Company Website should be contain a valid URI address"]')
COMPANY_WEB_SITE_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="Company Website is required"]')
COMPANY_LOGO_INPUT = (By.ID, 'icon-file')
COMPANY_LOGO_SIZE_ERROR_HINT = (By.CSS_SELECTOR, 'span.uploader_error__1PDAc')
DESCRIPTION_TEXT_AREA = (By.ID, 'description')
DESCRIPTION_IS_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="Description is required"]')
COUNTRY_DROP_DOWN_TRIGGER = (By.CSS_SELECTOR, '.location-form_countryField__1pdd0 .p-dropdown-trigger')
COUNTRY_DROP_DOWN_LIST = (By.CSS_SELECTOR, '.p-dropdown-items li.p-dropdown-item')
CITY_INPUT_FIELD = (By.ID, 'city')
CITY_IS_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="City is required"]')
POSTAL_CODE_INPUT_FIELD = (By.ID, 'postalCode')
POSTAL_CODE_IS_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="Postal Code is required"]')
ADDRESS_INPUT_FIELD = (By.ID, 'address')
ADDRESS_IS_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()="Address is required"]')
TERMS_CHECKBOX = (By.ID, 'agree')
TERMS_IS_REQUIRED_ERROR_HINT = (By.XPATH, '//small[text()=" is required"]')
STEP4_MODAL = (By.ID, '#pr_id_4')
SUCCESS_HEADER = (By.CSS_SELECTOR, '#pr_id_2 #pr_id_2_header')
SUCCESS_CLOSE_BUTTON = (By.CSS_SELECTOR, 'button.p-dialog-header-close')
CONFIRMATION_TEXT = (By.CSS_SELECTOR, '#registration-completion-form .completion_message__2mWsQ')
STATE_DROP_DOWN_TRIGGER = (By.CSS_SELECTOR,'.location-form_stateField__2zkI0 .p-dropdown-trigger')
STATE_DROP_DOWN_LIST = (By.CSS_SELECTOR,'.p-dropdown-items li')
CANADA_COUNTRY = (By.CSS_SELECTOR,'[aria-label="Canada"]')
INDIA_COUNTRY = (By.CSS_SELECTOR,'[aria-label="India"]')
USA_COUNTRY = (By.CSS_SELECTOR,'[aria-label="United States"]')
